
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Cart from "@/storage/Cart";
import Menu from "@/components/Menu"
import 'bootstrap/dist/css/bootstrap.min.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My shopping",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <Menu/>
        </header>
        <div className="w-full flex">
          <div className="w-4/5">{children}</div>
          <div className="">
            <Cart />
          </div>
        </div>
      </body>
    </html>
  );
}
