import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Cart from "@/storage/Cart"
import Menu from "@/components/Menu"
import "bootstrap/dist/css/bootstrap.min.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "My shopping",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <meta name='description' content='Welcome to my Next.js website!' />
        <meta property='og:title' content='My Awesome Next.js Site' />
        <meta
          property='og:description'
          content='Welcome to my Next.js website!'
        />
        <meta property='og:image' content='your-image-url' />
        <meta property='og:url' content='your-site-url' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css'
        />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css'
        />
        <title>{metadata.title}</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <Menu />
        </header>
        <div className='w-full flex'>
          <div className='w-4/5'>{children}</div>
          <div className='ml-4'>
            <Cart />
          </div>
        </div>
      </body>
    </html>
  )
}
